fix off_road_auto mapping
ValueError: Sensor sensor.rivian_dynamics_modes_drive_mode provides state value 'off_road_auto', which is not in the list of options provided